apiVersion: apps/v1
kind: Deployment
metadata:
  name: kro
  namespace: default
  labels:
    app.kubernetes.io/instance: kro
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: kro
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kro
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kro
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: kro
    spec:
      serviceAccountName: kro
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kro
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000
          image: "kro/controller"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metricsport
              containerPort: 8078
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 256m
              memory: 128Mi
          env:
            - name: KRO_METRICS_BIND_ADDRESS
              value: ":8078"
            - name: KRO_HEALTH_PROBE_BIND_ADDRESS
              value: ":8079"
            - name: KRO_RESOURCE_GROUP_CONCURRENT_RECONCILES
              value: "1"
            - name: KRO_DYNAMIC_CONTROLLER_CONCURRENT_RECONCILES
              value: "1"
            - name: KRO_LOG_LEVEL
              value: "3"
            - name: KRO_DYNAMIC_CONTROLLER_DEFAULT_RESYNC_PERIOD
              value: "36000"
            - name: KRO_DYNAMIC_CONTROLLER_DEFAULT_QUEUE_MAX_RETRIES
              value: "20"
            - name: KRO_GRACEFUL_SHUTDOWN_TIMEOUT
              value: "60s"
            - name: KRO_CLIENT_QPS
              value: "100"
            - name: KRO_CLIENT_BURST
              value: "150"
          args:
            - --metrics-bind-address
            - "$(KRO_METRICS_BIND_ADDRESS)"
            - --health-probe-bind-address
            - "$(KRO_HEALTH_PROBE_BIND_ADDRESS)"
            - --resource-graph-definition-concurrent-reconciles
            - "$(KRO_RESOURCE_GROUP_CONCURRENT_RECONCILES)"
            - --dynamic-controller-concurrent-reconciles
            - "$(KRO_DYNAMIC_CONTROLLER_CONCURRENT_RECONCILES)"
            - --log-level
            - "$(KRO_LOG_LEVEL)"
            - --graceful-shutdown-timeout
            - "$(KRO_GRACEFUL_SHUTDOWN_TIMEOUT)"
            - --dynamic-controller-default-resync-period
            - "$(KRO_DYNAMIC_CONTROLLER_DEFAULT_RESYNC_PERIOD)"
            - --dynamic-controller-default-queue-max-retries
            - "$(KRO_DYNAMIC_CONTROLLER_DEFAULT_QUEUE_MAX_RETRIES)"
            - --client-qps
            - "$(KRO_CLIENT_QPS)"
            - --client-burst
            - "$(KRO_CLIENT_BURST)"
            - --leader-elect
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8079
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8079
            initialDelaySeconds: 10
            periodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux