apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kro
  labels:
    app.kubernetes.io/instance: kro
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: kro
spec:
  jobLabel: kro
  namespaceSelector:
    matchNames:
      - kro-system
  selector:
    matchLabels:
      app.kubernetes.io/name: kro
      app.kubernetes.io/instance: kro
  endpoints:
    - port: metrics
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s