---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro-cluster-role
  annotations:
    kubernetes.io/description: |
      This ClusterRole grants cluster-wide admin access for the kro controller.
  labels:
    app.kubernetes.io/instance: kro
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: kro
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

