apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kro-cluster-role-binding
  labels:
    app.kubernetes.io/instance: kro
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: kro
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kro-cluster-role
subjects:
- kind: ServiceAccount
  name: kro
  namespace: default