resources:
# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
- service_account.yaml
- role.yaml
- role_aggregated.yaml
- role_binding.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kro
      app.kubernetes.io/component: controller
    includeTemplates: true
    includeSelectors: true

patches:
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kro:controller:static
        annotations:
          kubernetes.io/description: |
            This ClusterRole grants access for the kro controller to resources it always needs access to.
        labels:
          rbac.kro.run/aggregate-to-controller: "true"