apiVersion: v1
kind: ServiceAccount
metadata:
  name: kro
  namespace: default
  labels:
    app.kubernetes.io/instance: kro
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: kro
